# Site settings
baseurl = "https://ferrico.de/blog"
# themesDir = "../.."
languageCode = "en-us"
title = "ferrico blog"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
# disqusShortname = "spf13"

[params]
	name = "/blog"
	description = "ideas, project docs, and random thoughts"
	bio = "ideas, project docs, and random thoughts"
	# Enter optionally your twitter account
	twitter = "blayhem"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/custom.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	# subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "design âˆª code"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/blayhem"
    # facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/blayhem"
    # dribble  = "https://www.dribbble.com/"
    instagram = "https://instagram.com/blayhem"
